#!/bin/bash
set -e

# Load env vars for reference
source deploy/.env.template 2>/dev/null || true

echo "=== Render Deployment Guide ==="
echo ""
echo "Render has no CLI for deployment. Follow these steps:"
echo ""
echo "1. Go to https://dashboard.render.com"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub repository"
echo "4. Configure:"
echo "   - Name: bhxh-api"
echo "   - Runtime: Docker"
echo "   - Build Command: (leave empty for Docker)"
echo "   - Docker Context: /"
echo "   - Branch: main"
echo ""
echo "5. Add Environment Variables:"
echo "   API_KEYS=${API_KEYS}"
echo "   BHXH_BASE_URL=${BHXH_BASE_URL}"
echo "   BHXH_ENCRYPTION_KEY=${BHXH_ENCRYPTION_KEY}"
echo "   BHXH_USERNAME=${BHXH_USERNAME}"
echo "   BHXH_PASSWORD=${BHXH_PASSWORD}"
echo "   USE_PROXY=${USE_PROXY}"
echo "   EXTERNAL_PROXY_URL=${EXTERNAL_PROXY_URL}"
echo "   AI_CAPTCHA_ENDPOINT=${AI_CAPTCHA_ENDPOINT}"
echo "   AI_CAPTCHA_API_KEY=${AI_CAPTCHA_API_KEY}"
echo "   PORT=4000"
echo ""
echo "6. Click 'Deploy'"
echo ""
echo "Or use Render CLI (if installed):"
echo "  npm install -g render-cli"
echo "  render deploy"
echo ""
echo "For more info: https://render.com/docs/deploy-node-express-app"
